# Generated by Django 5.2.10 on 2026-01-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='faixa_alunos',
            field=models.PositiveIntegerField(choices=[(50, 'Até 50'), (65, 'Até 65'), (75, 'Até 75'), (100, 'Até 100')]),
        ),
    ]
