# Generated by Django 6.0 on 2026-01-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='anos_servico',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='professor',
            name='classes_leccionadas',
            field=models.ManyToManyField(blank=True, related_name='professores_alocados', to='academico.classe'),
        ),
        migrations.AddField(
            model_name='professor',
            name='formacao',
            field=models.CharField(blank=True, choices=[('N4', 'Nível 4 (N4)'), ('N3', 'Nível 3 (N3)'), ('N2', 'Nível 2 (N2)'), ('N1', 'Nível 1 (N1)')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='tipo_provimento',
            field=models.CharField(choices=[('PROVISORIO', 'Provisório'), ('DEFINITIVO', 'Definitivo')], default='PROVISORIO', max_length=20),
        ),
    ]
