# Generated by Django 6.0 on 2026-01-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_professor_anos_servico_professor_classes_leccionadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='area_formacao',
            field=models.CharField(blank=True, help_text='Obrigatório para N2 e N1', max_length=100, null=True),
        ),
    ]
