# Generated by Django 6.0 on 2026-01-07 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_professor_area_formacao'),
        ('core', '0004_alter_school_school_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordenadorClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.IntegerField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordenadores', to='academico.classe')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordenacoes_classe', to='academico.professor')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'verbose_name': 'Coordenador de Classe',
                'verbose_name_plural': 'Coordenadores de Classe',
                'unique_together': {('classe', 'school', 'ano_letivo')},
            },
        ),
        migrations.CreateModel(
            name='DelegadoDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.IntegerField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegados', to='academico.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegacoes_disciplina', to='academico.professor')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'verbose_name': 'Delegado de Disciplina',
                'verbose_name_plural': 'Delegados de Disciplina',
                'unique_together': {('disciplina', 'school', 'ano_letivo')},
            },
        ),
        migrations.CreateModel(
            name='DirectorTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.IntegerField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direccoes_turma', to='academico.professor')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
                ('turma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='director_turma', to='academico.turma')),
            ],
            options={
                'verbose_name': 'Director de Turma',
                'verbose_name_plural': 'Directores de Turma',
                'unique_together': {('professor', 'ano_letivo')},
            },
        ),
    ]
