# Generated by Django 6.0 on 2026-01-07 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_coordenadorclasse_delegadodisciplina_directorturma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='nome',
            new_name='nome_completo',
        ),
        migrations.AddField(
            model_name='aluno',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aluno',
            name='classe_atual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alunos_matriculados', to='academico.classe'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='contacto_encarregado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='aluno',
            name='encarregado_educacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='mae',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aluno',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aluno',
            name='pai',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(blank=True, choices=[('HOMEM', 'Homem'), ('MULHER', 'Mulher')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='situacao_social',
            field=models.CharField(choices=[('NENHUM', 'Nenhum'), ('ORFAO_PAI', 'Órfão de Pai'), ('ORFAO_MAE', 'Órfão de Mãe'), ('ORFAO_AMBOS', 'Órfão de Ambos')], default='NENHUM', max_length=20),
        ),
    ]
