# Generated by Django 6.0 on 2026-01-07 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_rename_nome_aluno_nome_completo_aluno_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='turma_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos_na_turma', to='academico.turma'),
        ),
    ]
