# Generated by Django 5.2.10 on 2026-01-09 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_professor_disciplinas_alter_aluno_id_alter_classe_id_and_more'),
        ('core', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='directorturma',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='coordenadorclasse',
            unique_together={('classe', 'school', 'ano_letivo'), ('professor', 'ano_letivo')},
        ),
        migrations.AlterUniqueTogether(
            name='delegadodisciplina',
            unique_together={('disciplina', 'school', 'ano_letivo'), ('professor', 'ano_letivo')},
        ),
    ]
