# Generated by Django 5.2.10 on 2026-01-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0008_alter_directorturma_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cargo_turma',
            field=models.CharField(default='Nenhum', help_text='Ex: Chefe de Turma, Adjunto, Higiene, etc.', max_length=100),
        ),
    ]
