# Generated by Django 5.2.10 on 2026-01-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0009_aluno_cargo_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('DESISTENTE', 'Desistente'), ('TRANSFERIDO', 'Transferido')], default='ATIVO', max_length=20),
        ),
    ]
