# Generated by Django 5.2.10 on 2026-01-15 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0012_disciplina_ordem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplina',
            options={'ordering': ['ordem', 'nome']},
        ),
    ]
