# Generated by Django 6.0 on 2026-01-07 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ACS', 'Avaliação Contínua Sistemática'), ('ACP', 'Avaliação de Controlo Parcial'), ('AT', 'Avaliação Trimestral'), ('EXAME', 'Exame Final')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('data_lancamento', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='academico.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.disciplina')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.turma')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
    ]
