# Generated by Django 6.0 on 2026-01-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_falta'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='trimestre',
            field=models.IntegerField(choices=[(1, '1º Trimestre'), (2, '2º Trimestre'), (3, '3º Trimestre')], default=1),
        ),
        migrations.AlterField(
            model_name='nota',
            name='tipo',
            field=models.CharField(choices=[('ACS', 'Avaliação Contínua Sistemática'), ('MAP', 'Avaliação Prática'), ('ACP', 'Avaliação Contínua Parcial'), ('EXAME', 'Exame Final')], max_length=10),
        ),
    ]
