# Generated by Django 5.2.10 on 2026-01-11 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0008_alter_directorturma_unique_together_and_more'),
        ('avaliacoes', '0004_alter_falta_id_alter_nota_id'),
        ('core', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='tipo',
            field=models.CharField(choices=[('ACS1', 'ACS 1'), ('ACS2', 'ACS 2'), ('ACS3', 'ACS 3'), ('MAP', 'Avaliação Prática (MAP)'), ('ACP', 'Avaliação Contínua Parcial (ACP)')], max_length=10),
        ),
        migrations.CreateModel(
            name='ResumoTrimestral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.IntegerField()),
                ('trimestre', models.IntegerField(choices=[(1, '1º Trimestre'), (2, '2º Trimestre'), (3, '3º Trimestre')])),
                ('macs', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Média ACS')),
                ('mt', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Média Trimestral')),
                ('com', models.CharField(blank=True, max_length=50, null=True, verbose_name='Classificação/Observação')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumos_trimestrais', to='academico.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.disciplina')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
                ('turma', models.ForeignKey(help_text='Turma onde o aluno obteve a nota', on_delete=django.db.models.deletion.CASCADE, to='academico.turma')),
            ],
            options={
                'verbose_name': 'Resumo Trimestral',
                'verbose_name_plural': 'Resumos Trimestrais',
                'unique_together': {('school', 'aluno', 'disciplina', 'ano_letivo', 'trimestre')},
            },
        ),
    ]
