# Generated by Django 6.0 on 2026-01-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='anos_servico',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tipo_provimento',
            field=models.CharField(choices=[('PROVISORIO', 'Provisório'), ('DEFINITIVO', 'Definitivo')], default='PROVISORIO', max_length=20),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='sector',
            field=models.CharField(blank=True, choices=[('SECRETARIA', 'Secretaria'), ('RH', 'Recursos Humanos'), ('APOIO', 'Apoio Administrativo')], max_length=50, null=True),
        ),
    ]
