# Generated by Django 5.2.10 on 2026-01-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0005_alter_funcionario_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='sector',
            field=models.CharField(blank=True, choices=[('DIRECAO', 'Direção/Gestão'), ('SECRETARIA', 'Secretaria'), ('RH', 'Recursos Humanos'), ('APOIO', 'Apoio Administrativo')], max_length=50, null=True),
        ),
    ]
