# Generated by Django 6.0 on 2026-01-07 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalheEscola',
            fields=[
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detalhes', serialize=False, to='core.school')),
                ('endereco', models.TextField(blank=True)),
                ('contacto', models.CharField(blank=True, max_length=50)),
                ('email_institucional', models.EmailField(blank=True, max_length=254)),
                ('ensino_primario', models.BooleanField(default=False)),
                ('ensino_secundario_geral', models.BooleanField(default=False)),
                ('ensino_tecnico_profissional', models.BooleanField(default=False)),
                ('infraestrutura_info', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Detalhe da Escola',
                'verbose_name_plural': 'Detalhes das Escolas',
            },
        ),
    ]
