# Generated by Django 6.0 on 2026-01-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN_SISTEMA', 'Admin do Sistema'), ('SDEJT_RAP', 'SDEJT - Repartição de Adm e Planificação'), ('SDEJT_REG', 'SDEJT - Repartição de Ensino Geral'), ('ADMIN_ESCOLA', 'Director da Escola'), ('DAP', 'Director Adjunto Pedagógico'), ('PROFESSOR', 'Professor'), ('ADMINISTRATIVO', 'Sector Administrativo')], max_length=30),
        ),
    ]
