# Generated by Django 6.0 on 2026-01-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('PRIMARIA', 'Ensino Primário (1ª-6ª Classe)'), ('BASICA', 'Ensino Básico (1ª-9ª Classe)'), ('SECUNDARIA_1', 'Ensino Secundário - 1º Ciclo (7ª-9ª Classe)'), ('SECUNDARIA_2', 'Ensino Secundário - 2º Ciclo (10ª-12ª Classe)'), ('SECUNDARIA_COMPLETA', 'Ensino Secundário Completo (7ª-12ª Classe)')], default='PRIMARIA', max_length=20),
        ),
    ]
